config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :chats, only: [:index, :create] 

    namespace :api do
      resources :chats, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  validates :message, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
  belongs_to :group
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :chats
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_chat = chats.last).present?
      last_chat.message? ? last_chat.message : "画像が投稿されています"
    else
      "まだメッセージはありません"
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :chats
  validates :name, presence: true
end

app/controllers/api/chats_controller.rb
class Api::ChatsController < ApplicationController
  def index
    # ルーティングでの設定によりparamsの中にgroup_idというキーでグループのidが入るので、これを元にDBからグループを取得する
    group = Group.find(params[:group_id])
    # ajaxで送られてくる最後のメッセージのid番号を変数に代入
    last_chat_id = params[:id].to_i
    # 取得したグループでのメッセージ達から、idがlast_message_idより新しい（大きい）メッセージ達のみを取得
    @chats = group.chats.includes(:user).where("id > #{last_chat_id}")
  end
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    # ルーティングでの設定によりparamsの中にgroup_idというキーでグループのidが入るので、これを元にDBからグループを取得する
    group = Group.find(params[:group_id])
    # ajaxで送られてくる最後のメッセージのid番号を変数に代入
    last_chat_id = params[:id].to_i
    # 取得したグループでのメッセージ達から、idがlast_message_idより新しい（大きい）メッセージ達のみを取得
    @messages = group.chats.includes(:user).where("id > #{last_chat_id}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_group

  def index
    @chat  = Chat.new
    @chats = @group.chats.includes(:user)
  end

  def create
    @chat = @group.chats.new(chat_params)
    if @chat.save
      respond_to do |format|
        format.html { redirect_to group_chats_path(@group), notice: 'メッセージが送信されました' }
        format.json
      end
    else
      @chats = @group.chats.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  
  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_chats_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, {:user_ids => []})
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def index
    @users = User.where('name LIKE(?)', "%#{params[:search]}%" ).where.not(id: current_user.id)
    respond_to do |format|
      format.html
      format.json 
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/_chat.html.haml
.chat{data: {message_id: chat.id }}
  .chat__upper
    %p.chat__upper--talker
      = chat.user.name
    %p.chat__upper--date
      = chat.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[chat.created_at.wday]})%H:%M:%S")
  .chat__content
    %p.chat__content__message<
      - if chat.message.present?
        = chat.message
    = image_tag chat.image.url, class: 'chat__content__image' if chat.image.present?

app/views/chats/index.html.haml
.wrapper
  = render "shared/side_bar"    
  .chat-main
    .main-header
      .header-left
        %p.header-left__group
          = @group.name
        %p.header-left__members
          Member: 
          - @group.users.each do |group_user|
            = group_user.name
      = link_to edit_group_path(@group), class: 'main-header__edit' do
        Edit
    .chats      
      = render partial: 'chat', collection: @chats
    .form
      = form_for [@group, @chat] do |f|
        .input-box
          .input-box__message
            = f.text_field :message, class: "input-box__message__text", placeholder: "type a message"
            = f.label :image ,class: "input-box__message__image" do
              = fa_icon "picture-o"
              = f.file_field :image, class: "input-box__message__image--file"
          = f.submit 'Send', class: "input-box__sent"

app/views/groups/_form.html.haml
= form_for group do |f|
  - if @group.errors.any?
    .chat-group-form__errors
      %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました"
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message

  .chat-group-form__field
    .chat-group-form__field--left
      = f.label 'グループ名', class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat_group_name chat-group-form__input', placeholder: "グループ名を入力してください"

  .chat-group-form__field
    .chat-group-form__field--left
      =f.label 'チャットメンバーを追加', class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chatchat-group-form__search.clearfix
        = text_field_tag :search, '', class: 'chat-group-form__input', id: 'user-search-field', placeholder:'追加したいユーザー名を入力してください'
      .user-search-result

  .chat-group-form__field
    .chat-group-form__field--left
      = f.label 'チャットメンバー', class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-users
        - @group.users.each do |user|
          .chat-group-user
            %input{name: 'group[user_ids][]', type: 'hidden', value: "#{user.id}"}
            %p.chat-group-user__name 
              = user.name
            .user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 
              削除
      
  .chat-group-form__field
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn' 

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper

  =render 'shared/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/shared/_side_bar.html.haml
.chat-side
  .side-header
    .side-header__box
      %p.side-header__box__user<
        = current_user.name
      %ul.side-header__box__menu
        %li.side-header__box__menu--edit
          = link_to new_group_path do
            = fa_icon 'edit'
        %li.side-header__box__menu--cog
          = link_to edit_user_path(current_user) do
            = fa_icon 'cog'
  .side-groups
    - current_user.groups.each do |group|
      = link_to group_chats_path(group) do
        .side-group
          %p.side-group__name
            = group.name
          %p.side-group__message
            = group.show_last_message

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'